---
title: "Tony's Initial Idea (2020-10-17)"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# Intro

**Big Idea**: Analyze the risk-reward---quantified by expected points
added (EPA)---of different approaches a defensive player might take to
break up a pass.

Assuming the defender is close enough to make a play on either the ball
or the the receiver as the ball is arriving to the receiver, the common
cases (anecdotally) are as follows:

1.  Defender tries to cut in front of the receiver and...

    1.  deflects the ball and no catch is made. ***Positive EPA (for
        defense)***

    2.  intercepts the ball. ***Positive EPA***

    3.  receiver makes the catch. ***Negative EPA***[^1]

[^1]: Receiver is likely to gain more yards in this case because the
    defender is not left in a good position to make a tackle.

```{=html}
<!-- -->
```
2.  Defensive player intends to hit the receiver upon the ball arriving
    and...

    1.  hits the receiver BEFORE the ball arrives (presumably the
        receiver does not make the catch) and...

        1.  a penalty is called on the defense.[^2] ***Negative EPA***

        2.  a penalty is NOT called.[^3] ***Positive EPA***[^4]

    2.  hits the receiver AFTER the ball arrives and...

        1.  the receiver makes the catch successfully. ***Negative
            EPA***

        2.  the receiver drops the ball (perhaps forced by the defender,
            but maybe not).[^5] ***Positive EPA***

[^2]: Whether or not a catch is made is irrelevant in nearly all cases.
    Cases where it's not irrelevant: coach of offensive team does not
    accept penalty because the field position made by the catch is
    greater than that which would be gained from accepting the penalty.

[^3]: Player likely does not make the catch (although it's not
    impossible).

[^4]: Risk taken by defender, whether intentional or not, is rewarded.

[^5]: If we filter plays down to just those where a receiver has a
    defender in relatively close defender, then we can sort of assume
    that the drop is at least partially forced. If there were no
    defender around, it is more likely a pure drop by the receiver. In
    either case, it's also possible that the pass was bad, so a catch
    was very unlikely anyways. I don't want to bother with a catch
    probability model at this time, but it could be interesting to use
    it for something like this.

This isn't a complete tree:

-   There are other possibilities for penalties directly related to the
    receiver or defender not mentioned above. (We should probably ignore
    penalties unrelated to the receiver-defender interaction.) EPA would
    depend on which team the penalty is called on.

-   There are also other ways in which an interception can occur, e.g.
    the defender hits the receiver after the catch, causing the ball to
    be juggled and end up in a defenders hands.

# Meeting Evaluation Criteria

(This isn't all of the evaluation criteria, just the things that are
relevant to framing our initial approach.)

## **Innovation**

-   ***Are the proposed findings actionable?***

    Defensive backs could be taught EPA-optimal tendencies depending on
    the finding. For example, if we find that hitting the receiver just
    prior to the ball reaching the receiver actually is worth the risk
    of getting called for a penalty (perhaps because officials don't
    call it enough or the EPA change is favorable compared to allowing
    the catch), then defensive backs may be told to be more aggressive
    with how they attack the ball.

-   ***Is this a way of looking at tracking data that is novel?***

    Identifying instances where a defender cuts in front of a receiver
    to make a play on the ball or where a defender hits a receiver just
    before or after the ball arrives is not something that is not
    discussed in the literature (as the academia folk would say).

## **Relevance**

-   ***Would NFL teams (or the league office) be able to use these
    results on a week-to-week basis?***

    Coaches could show their defensive backs instances where they could
    have acted differently (or did act "optimally") in instances where
    they close in on a receiver attempting to make a catch.

-   ***Does the analysis account for variables that make football data
    complex?***

    Dealing with penalties will be a pain in the ass. So yes, we'll have
    to account for some weird shit.

# Modeling

For modeling, I imagine EPA would be the target variable. The main
predictor would be a categorization of the defender's attack of the
ball/receiver as the ball arrives (as described in the tree). Other
variables could be

-   x,y of ball at snap (to provide context of field position)

-   Time (higher risk towards end of game)

-   Score (higher risk in close game)

-   x,y of targeted receiver, closest defender at time of arrival, and
    ball at throw

-   x,y of ball at arrival[^6]

[^6]: Not sure if it makes sense to use the x,y of targeted receiver and
    defender of interest at this point

The initial ball position is sort of already encoded in EPA, so there
may be some undesire-able correlation there.
